from .gelbooru_tags import NODE_CLASS_MAPPINGS as G_CLASS, NODE_DISPLAY_NAME_MAPPINGS as G_NAME
from .load_two_gguf_unets import NODE_CLASS_MAPPINGS as T_CLASS, NODE_DISPLAY_NAME_MAPPINGS as T_NAME

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(G_CLASS)
NODE_CLASS_MAPPINGS.update(T_CLASS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(G_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(T_NAME)